name: ci

env:
  GO_VERSION: 1.24.4

# on:
#   push:
#     branches-ignore:
#       - main
#   pull_request:
#     branches:
#       - main

on:
  push:
    - main


jobs:
  golint:
    name: go-lint
    runs-on: ubuntu-latest
    steps:
      # https://github.com/actions/checkout
      - name: Checkout source code
        uses: actions/checkout@v4

      # https://github.com/actions/setup-go  
      - name: Download go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      # https://github.com/golangci/golangci-lint-action
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.1.6

  gosec:
    name: gosec
    runs-on: ubuntu-latest
    steps:
      # https://github.com/actions/checkout
      - name: Checkout source code
        uses: actions/checkout@v4
        
      # https://github.com/marketplace/actions/gosec-security-checker
      - name: Run Gosec Security Scanner
        uses: securego/gosec@master
        with:
          args: ./...
    
  govulncheck:
    name: govulncheck
    runs-on: ubuntu-latest
    steps:
    # https://github.com/golang/govulncheck-action
    - name: Run govulncheck vulnerabilities scanner 
      uses: golang/govulncheck-action@v1
      with:
          go-version-input: ${{ env.GO_VERSION }}
          go-package: ./...

  gotest:
    name: go-test
    runs-on: ubuntu-latest
    steps:
      # https://github.com/actions/checkout
      - name: Checkout source code
        uses: actions/checkout@v4

      # https://github.com/actions/setup-go  
      - name: Download Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Run Go tests
        run: |
          go test -v ./...

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [golint, gosec, govulncheck, gotest]
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      # https://github.com/actions/checkout
      - name: Checkout source code
        uses: actions/checkout@v4

      # https://github.com/actions/setup-go  
      - name: Download Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Build binaries
        run: |
          mkdir -p dist
          VERSION=${GITHUB_REF##*/}
          echo "Building version $VERSION"
          GOOS=linux GOARCH=amd64 go build -o dist/cf-ip-ranges-exporter-$VERSION-linux-amd64 ./...
          GOOS=windows GOARCH=amd64 go build -o dist/cf-ip-ranges-exporter-$VERSION-windows-amd64.exe ./...

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/*

